version: "3.9"
services:
  mongo-db:
    image: mongo
    ports:
      - "27017:27017"
    container_name: mongo-db
    volumes:
      - ./db/:/data/db
  basf_challenge:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    container_name: basf_challenge
    links:
      - mongo-db
