server:
  port : 8082

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      #uri: mongodb://host.docker.internal/basf
      uri: mongodb://mongo-db:27017/basf
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB